### ISSUE TITLE
Support for decision tables?

### ISSUE THREAD

**Issue by sgrewal-mphrx** [kensiprell/grails-drools#4]
Is there any plan for supporting decision tables, through spreadsheets, in the plugin?

**Comment by kensiprell** [comment]
That's not something I'd considered; however, it might be doable. I'm not a Drools expert, so how should this work? 

I can imagine something simple like having a separate directory for decision table files (csv, xls, etc.) similar to `src/resources/rules` that are converted to drl files and placed on the classpath. Would this meet your needs?

**Comment by sgrewal-mphrx** [comment]
Appreciate the quick reply Ken. Even I’m relatively new to drools, hence I’m reading up on the decision tables part as of now. Will get back to you shortly on how exactly it should work, but that’s something we would prefer.

I have a couple of other questions as to why these aren’t supported?

  *   Externalising the rule/drl/xls files, so a change does not require a fresh deployment of war. Any specific reason why the location is fixed?
  *   Any changes in rules requires a server restart. Can’t we re-compile them at run-time and load them into the rule base/re-build the rule base dynamically?

**Comment by kensiprell** [comment]
I'm working on a 1.1 branch that will adapt to changes in drl files in development mode by copying them to the appropriate location and reloading the beans. I'm not sure that doing something like this in production is a good idea; however, I'm open to suggestions.

One option is to store the rules in a database, which is how I plan on working with non-static rules. Also, version 1.1 will allow you to call DroolsService with rules defined in a `String`, which would be another option for handling dynamic rules.
