### ISSUE TITLE
Can't read DRL files once compiled in EAR format

### ISSUE THREAD

**Issue by lvazquezt** [kensiprell/grails-drools#8]
Hi,

I am using Grails 2.3.11 and 1.0.1 for the plugin. I haven't modified grails.plugin.drools.drlFileLocation and I have my rules in src/resources/rules/rules2012.
In DroolsConfig.groovy I have packages: "rules2012" (also tried packages: "rules.rules2012").

When running in local from IntelliJ I have no problems and works perfectly fine. When I deploy to our dev environment I do not reach the DRL files. I know because I have this code.
```groovy
private countRules() {
    logger.info("Calculating number of rules in this KieBase")
    Iterable<KiePackage> packages = kBase2012.getKiePackages();
    for (KiePackage p : packages) {
      Collection<Rule> allRules = p.getRules();
      if (allRules.size() > 0)
        logger.info(allRules.size() + " rules loaded from package " + p.getName());
    }
  }
```

When running in my local machine I log this:
Calculating number of rules in this KieBase
- 85 rules loaded from package sec.rules.rules2012

When running in the server I log:
Calculating number of rules in this KieBase

My DroolsConfig:
```groovy
kieBases = [
        [
                includeInConfig: true,
                attributes     : [
                        name    : "kBase2012",
                        default : false,
                        packages: "rules2012"
                ],
                kieSessions    : [
                        [
                                includeInConfig: true,
                                attributes     : [
                                        name   : "statefulSession2012",
                                        default: false,
                                        type   : "stateful"
                                ],
                                kieListeners   : [
                                    [
                                        includeInConfig: false,
                                        type           : "agendaEventListener",
                                        debug          : false,
                                        //ref            : "beanNameFromKieEventListenersList",
                                        nestedBeanClass: "sec.project.CustomAgendaEventListener"
                                    ]
                                ]
                        ]
                ]
        ]
```

In my ear file the DRL files end up in:
myProject\WEB-INF\classes\rules\rules2012\

Is the same if I compile it in a war package. 

Any ideas what am I doing wrong?

Thank you,
Lino

**Comment by kensiprell** [comment]
Lino,
Does this happen on Windows? If so, I'll have a fix out for it this weekend.

I'm still puzzled about your other issue.

Ken

**Comment by lvazquezt** [comment]
Hi Ken,

Yes I am using Windows. Thanks for you quick answer.

About the other issue, I did a bit of refactoring so I don't have 2 classes named the same way and it's gone. My theory is that is a problem on how Grails generates internal names for classes and Domain class objects. Is not good practice to have two classes named the same way so no problem changing it. I'll let you know if I discover something new about it.

Lino

**Comment by lvazquezt** [comment]
Hi Ken,

Sorry but before maybe I didn't understand. I am developing on Windows but the servers are running Linux.

Lino

**Comment by kensiprell** [comment]
Lino,

I didn't make myself clear. I was asking if your server is running on Windows, so now I'm puzzled again. Where is the "sec" coming from in the line below? I don't see that in your directory structure.

85 rules loaded from package sec.rules.rules2012

Ken

**Comment by kensiprell** [comment]
Lino,

Another thought. Does your server explode the the EAR or run from the archive. If it's exploded, does the path to the rules look right? On Linux it should be under WEB-INF/classes/rules/rules2012/. Another user with a similar issue was running his server on Windows, so I thought you might have the same problem.

Ken

**Comment by lvazquezt** [comment]
Ken,

I checked what you said about "sec" and a few DRL classes had the package path wrongly defined. I forgot to change it after the migration. Now is correct (everything is under rules.rules2012 and defined like that) and I still have the same problem.

I have checked the EAR file and the path looks right, WEB-INF/classes/rules/rules2012/

Lino

**Comment by lvazquezt** [comment]
Ken,

I just remembered something. In order to have the DRL files in the EAR file, I had to add this two lines to my config.groovy

gails.resources.adhoc.includes = ['/rules/**']
gails.resources.adhoc.patterns = ['/rules/*']

Otherwise, they were ignored. Is this normal or they are supposed to be added automatically? Maybe the problem is related.

Lino

**Comment by kensiprell** [comment]
Lino,

How are you creating the EAR? I should have asked this sooner since there's not a create-ear script as far as I know. [These lines](https://github.com/kensiprell/grails-drools/blob/master/scripts/_Events.groovy#L17-L19) take care of getting the rules files into the `classes` directory in the WAR. If the files end up in the right place, I assume the script you're using triggers the `createWarStart` event. By the way I experimented with putting the files in the WAR resources directory, but I had problems with that, so that's why they're in `classes`.

Using the resources plugin to manage the rule files is probably not a good idea. If they are in two places on the classpath, maybe the Drools engine is confused about which ones to use. I don't understand why those two lines are necessary.

Ken

**Comment by kensiprell** [comment]
Lino,

Please try version 1.1.0 and let me know if it helps with any of your problems.

Ken

**Comment by lvazquezt** [comment]
Hi Ken,

This is really odd. With the new version I get redirected to some login page that is not ours. I think is the default login for Spring Security. I have checked and is that for sure because if I go back to version 1.0.1 works fine again.

Lino

**Comment by kensiprell** [comment]
Lino,

I've been working with the Spring Security plugin for a couple of years, and I can't imagine how the Drools plugin would interfere with it. Plus, the changes to 1.1 are minimal. Are you simply changing the plugin version and nothing else and then testing your application, or are you reseting a git commit or something like that?

Ken

**Comment by majkelo** [comment]
@kensiprell I'm afraid I've received error connected with oauth2, too. Please check it out:
http://stackoverflow.com/questions/30438819/drools-make-conflict-with-spring-security-oauth2-provider
Mike

**Comment by kensiprell** [comment]
Thanks, @majkelo. As soon as I saw your stracktrace I knew we had a version conflict. The cxf plugin uses the same "com.sun.xml.bind:jaxb-impl" and "com.sun.xml.bind:jaxb-xjc" [version](https://github.com/Grails-Plugin-Consortium/grails-cxf/blob/master/grails-app/conf/BuildConfig.groovy#L9) as my [plugin](https://github.com/kensiprell/grails-drools/blob/master/grails-app/conf/BuildConfig.groovy#L21), which overrode whatever other versions were being used in your application, thereby resolving the conflict.

Another fix is to add something like the example below to your `BuildConfig.groovy`, changing the version as necessary:
```
grails.project.dependency.resolution = {
    dependencies {
        String comSunXmlBindVersion = "2.2.11"
        runtime "com.sun.xml.bind:jaxb-xjc:$comSunXmlBindVersion", {
            excludes "jaxb-core"
        }
        runtime "com.sun.xml.bind:jaxb-impl:$comSunXmlBindVersion", {
           excludes "FastInfoset", "jaxb-core"
        }
    }
}
```

@lvazquezt I'm going to close this issue. If you're still having problems with the EAR file using version 1.1, please reopen it. 

Ken
